### PR TITLE
Update Debugger.php

### PR DESCRIPTION
**Pull request by 9585999**
solution 
#37
https://github.com/roots/sage/issues/1936

### CODE REVIEW

**Comment by darrenjacoby** [comment]
Just waiting out on this merge until the Sage solution is final.

**Comment by darrenjacoby** [comment]
Sage fix has been merged, so will merge this over the weekend.

**Comment by darrenjacoby** [comment]
thank you @9585999 !

**Comment by 9585999** [comment]
@darrenjacoby NP 😄

**Pull request merged**
