### PR TITLE
Fix issue #70

### PR DESCRIPTION
**Pull request by slackday**
Update brain/hierarchy to 2.4.0 to fix page template issue

### CODE REVIEW

**Comment by slackday** [comment]
@darrenjacoby could you look at this please?

**Comment by darrenjacoby** [comment]
merged to dev-master. sorry for the delay, been swamped this side before holidays.

**Comment by slackday** [comment]
Thanks for taking your time to look at this! And hope it sorts itself with your other stuff before holidays 👍

**Comment by slackday** [comment]
@darrenjacoby Sorry to bother again. Any chans you could tag v2.1.1 with todays changes?

**Comment by briggySmalls** [comment]
Would also love to get a version since my pull request (#105) was merged!

**Comment by darrenjacoby** [comment]
I'll get it tagged tomorrow, just on a deadline for the end of this week.

**Comment by briggySmalls** [comment]
Thank you so much! 🙇 😍

**Comment by briggySmalls** [comment]
Woop woop just seen the release 👏

**Pull request merged**
