### PR TITLE
add filter to dump()

### PR DESCRIPTION
**Pull request by 9585999**
add filter for dump() function

### CODE REVIEW

**Comment by darrenjacoby** [comment]
@9585999 this looks good! Can't thank you enough for your work on the debugger, I'll merge soon.

**Comment by 9585999** [comment]
@darrenjacoby No problem :).

I by the way solved a problem https://github.com/soberwp/controller/issues/43 with a conclusion of unnecessary variables in var_dump (), using this filter.

```php
add_filter('sober/controller/dump', function ($data) {
    $data = collect($data)->except([
        'loop', 'query', 'term', '__currentLoopData'
    ])->all();

    dump($data);
});
```

But the solution is not universal, because variables remain in the Controller Debugger ... This can be seen in the screenshot.
img_2017-08-31_ _12_00_46

**Comment by 9585999** [comment]
@darrenjacoby How do you look at it to hang a filter on the `sanitize()` function?

```php

protected function sanitize()
{
    $data = array_diff_key($this->data['__data'], array_flip(['__env', 'app', 'obLevel']));
    $this->data = has_filter('sober/controller/sanitize') ? apply_filters('sober/controller/sanitize', $data) : $data;
}
```

This gives control over the output **data in the debugger**:
```php

add_filter('sober/controller/sanitize', function ($data) {
    $data = collect($data)->except([
        'loop', 'query', 'term', '__currentLoopData'
    ])->all();

    return $data;
});
```
img 2017-08-31 13 34 27

**Comment by darrenjacoby** [comment]
I like that. I think we need to be more explicit with the filter name though, something like sober/controller/debugger/sanitize unless ultimately this could be added to the actual Controller as well. Let me check that out.

**Comment by 9585999** [comment]
@darrenjacoby Of course, without any problems :),
 and by the names of the filters I think really `sober/controller/debugger/*` a more telling name.

**Comment by darrenjacoby** [comment]
@9585999 

All PR's look good, only thing I would prefer is to not add color to the Debugger output. I do like the idea of adding formatting though, and wrapping in a class so that the developer can assign their own styles. Similar to how the Sass partial tinymce in Sage works.

**Comment by 9585999** [comment]
@darrenjacoby 

```html
<font color="#cc0000"> => <font class="count">
<font color='#888a85'> => <font>
```
How do you look at this option?

**Comment by darrenjacoby** [comment]
@9585999 

I think we're going to need to use a class name that is 'safe', and wouldn't conflict with other styles. Perhaps something prefixed, `-controller-debugger` and then append from there. `-controller-debugger-count` etc. `<font>` also isn't considered valid HTML5, so `<span>` would be more appropriate for text based classes, otherwise a div for the wrapper. I'm happy to edit after merging your PR.

**Comment by 9585999** [comment]
@darrenjacoby Let me then while I remove these changes? https://github.com/soberwp/controller/commit/6bcc83200c6069edc48c81a9f2b165e05a56c719

**Comment by darrenjacoby** [comment]
@9585999 

Yea cool, I'll add in some classes and merge over the weekend! Thanks for contributing so much, it's such a big help.

**Pull request closed without merging**
