### PR TITLE
Update Debugger.php

### PR DESCRIPTION
**Pull request by 9585999**
complete replacement of var_dump() with @debug() in blade templates.

### CODE REVIEW

**Comment by darrenjacoby** [comment]
Hey @9585999, just curious why you closed it? 

There is a default for @debug as is though, is that what you were trying to accomplish with the revised code?

**Comment by 9585999** [comment]
@darrenjacoby Sometimes it becomes necessary to use the template blade `var_dump()`, and do it all the time through `@php(var_dump($data))` not very convenient, much more convenient byloby via `@debug($data)`, but the proposed solution is not finalized ...

**Comment by darrenjacoby** [comment]
@9585999 how would that differ from @debug('dump') ? It's also a var_dump.

**Comment by 9585999** [comment]
@darrenjacoby For example, if I use WP_Query, I often use var_dump($query) ...

**Comment by darrenjacoby** [comment]
OK, so you're just trying to var_dump the Controller data, is that correct?

**Comment by 9585999** [comment]
`@debug()` has its own options, `dump, hierarchy, controller`, they work well, I do not see anything wrong with the fact that the `@debug()` directive can perform the usual `var_dump()` if necessary ...

**Pull request closed without merging**
